[package]
name = "libctr-rs"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
cstr_core = "0.2"
static_assertions = "1.1"
hashbrown = "0.11"
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
safe-transmute = { version = "0.11", default-features = false }
num_enum = { version = "0.5", default-features = false }

[target.'cfg(target_os = "horizon")'.dependencies]
ctru-sys = { git = "https://github.com/zaksabeast/ctru-rs" }

[target.'cfg(not(target_os = "horizon"))'.dependencies]
mocktopus = { version = "0.7.11" }

[features]
log = []

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
